version: '3.4'
services:
  web.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"

    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  
  personservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5006;
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://c_personservice:5006
      - ConsulConfig__ServiceName=PersonServie
      - ConsulConfig__ServiceId=person
    ports:
      - "5006:5006"
 
    depends_on:
      - web.apigateway
      - s_postgresql
      - s_consul
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  reportservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://c_personservice:5005
      - ConsulConfig__ServiceName=ReportServie
      - ConsulConfig__ServiceId=report
    ports:
      - "5005:5005"
 
    depends_on:
      - web.apigateway
      - s_postgresql
      - s_consul
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  s_consul:
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp 

  
  s_rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  s_postgresql:
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    

    
